# ==============================================================================
# LAVALINK NODE 3 - US-EAST (Primary Americas)
# Production-Grade Configuration with Anti-Block & Multi-IP Routing
# ==============================================================================

server:
  port: 2335
  address: 0.0.0.0
  http2:
    enabled: true

spring:
  main:
    banner-mode: log

# ========================
# CLUSTER CONFIGURATION
# ========================
cluster:
  node:
    id: "ll-node-3"
    region: "us-east"
    priority: 1
    tags:
      - "americas"
      - "primary"
      - "low-latency"

# ========================
# YOUTUBE PLUGIN (Anti-Block Premium)
# ========================
plugins:
  youtube:
    enabled: true
    
    clients:
      - "MUSIC"
      - "ANDROID_MUSIC"
      - "IOS"
      - "WEB"
      - "TVHTML5EMBEDDED"
      - "ANDROID_VR"
      - "TV"
      - "MWEB"
      - "WEBEMBEDDED"
    
    clientOptions:
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: false
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      WEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      MWEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
    
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN}"
      skipInitialization: false
    
    remoteCipher:
      url: "${CIPHER_SERVER_URL:http://cipher-server:8001}"
      password: "${CIPHER_PASSWORD}"
    
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

  lavasrc:
    providers:
      - "scsearch:%QUERY%"
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: true
      deezer: true
      youtube: true
      soundcloud: true
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      countryCode: "${SPOTIFY_COUNTRY:US}"
      playlistLoadLimit: 10
      albumLoadLimit: 10
      resolveArtistsInSearch: true
      localFiles: false
    applemusic:
      countryCode: "${APPLE_COUNTRY:US}"
      mediaAPIToken: "${APPLE_MUSIC_TOKEN}"
      playlistLoadLimit: 10
      albumLoadLimit: 10
    deezer:
      masterDecryptionKey: "${DEEZER_MASTER_KEY}"
      arl: "${DEEZER_ARL}"
      formats:
        - "FLAC"
        - "MP3_320"
        - "MP3_256"
        - "MP3_128"

  lavalyrics:
    sources:
      - spotify
      - youtube
      - deezer
      - lrclib

  sponsorblock:
    enabled: true

lavalink:
  plugins:
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
      snapshot: false
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      snapshot: false
    - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1"
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.14.0"
      snapshot: false
  pluginsDir: "./plugins"
  
  server:
    password: "${LAVALINK_PASSWORD:SecurePassword123!}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    
    nonAllocatingFrameBuffer: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    
    httpConfig:
      proxyHost: "${PROXY_HOST:proxy-router}"
      proxyPort: ${PROXY_PORT:9000}
      proxyUser: "${PROXY_USER:}"
      proxyPassword: "${PROXY_PASSWORD:}"

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: "${SENTRY_DSN:}"
  environment: "production"
  tags:
    node: "ll-node-3"
    region: "us-east"

logging:
  file:
    max-history: 30
    max-size: 50MB
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
    lavalink.server.io.SocketContext: WARN
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: WARN
    dev.lavalink.youtube.YoutubeAudioSourceManager: INFO
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
